# Reference this view as products
schema: public

dimensions:
  cost: {}
  category: {}
  name: {}
  sku: {}

  department:
    label: TEST 2
    tags: [ test_tag ]

  retail_price:
    sql: '"RETAIL_PRICE"'
    label: TEST
    tags: [ test_tag ]

  id:
    format: ID
    primary_key: true

  distribution_center_id:
    format: ID

measures:
  count:
    aggregate_type: count

  name_count_distinct:
    sql: ${products.name}
    aggregate_type: count_distinct

  category_count_distinct:
    sql: ${products.category}
    aggregate_type: count_distinct
