# Reference this view as products
schema: public

dimensions:
  cost: {}
  category: {}
  name: {}
  department: {}
  sku: {}

  retail_price:
    sql: '"RETAIL_PRICE"'
    label: TEST
    tags: [ test_tag ]

  id:
    format: ID
    primary_key: true

  distribution_center_id:
    format: ID

measures:
  count:
    aggregate_type: count
